import HautevilleHouse.ChemicalEngineeringDistillationLemmaCanonicalLaneLean.DistillationPhaseEquilibrium
import HautevilleHouse.ChemicalEngineeringDistillationLemmaCanonicalLaneLean.DistillationColumnDesign
import HautevilleHouse.ChemicalEngineeringDistillationLemmaCanonicalLaneLean.DistillationMcCabeThieleMethod
import HautevilleHouse.ChemicalEngineeringDistillationLemmaCanonicalLaneLean.DistillationFenskeUnderwoodGilliland
import HautevilleHouse.ChemicalEngineeringDistillationLemmaCanonicalLaneLean.DistillationRateBasedModel
import HautevilleHouse.ChemicalEngineeringDistillationLemmaCanonicalLaneLean.DistillationFinalTheorem

namespace HautevilleHouse
namespace ChemicalEngineeringDistillationLemmaCanonicalLaneLean

theorem distillation_package_imported : True := True.intro

def distillationModuleCount : Nat := 6

end ChemicalEngineeringDistillationLemmaCanonicalLaneLean
end HautevilleHouse